language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t denzelsan91/react-test -f ./client/Dockerfile.dev ./client

script:
  -  docker run -e CI=true denzelsan91/react-test npm test

after_success:
  - docker build -t denzelsan91/multi-client -f ./client
  - docker build -t denzelsan91/multi-nginx -f ./nginx
  - docker build -t denzelsan91/multi-server -f ./server
  - docker build -t denzelsan91/multi-worker -f ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push denzelsan91/multi-client
  - docker push denzelsan91/multi-nginx
  - docker push denzelsan91/multi-server
  - docker push denzelsan91/multi-worker